services:
  nginx:
      image: nginx:1-alpine
      ports:
        - "8000:80"
      volumes:
        - ./html5up-stellar/:/usr/share/nginx/html
  mongo:
    image: mongo:8.0
    ports:
      - "127.0.0.1:27017:27017"
  snake:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
      DOCKER_DB: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app  
      - ./logs:/app/logs
