services:
  mongo:
    image: alfg/nginx-rtmp
  snake:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
      DOCKER_DB: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app  
      - ./logs:/app/logs
